### ISSUE TITLE
sub-machine refrence ignored after adding a state 

### ISSUE THREAD

**Issue by goldenboyt** [spring-projects/spring-statemachine#288] opened 2016-12-05 08:36 UTC
version: 1.2.0.RC1
model: [simple-submachineref](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/simple-submachineref.uml)

In parent diagram if i add a state after s2, all sub-machine  of s2 will be ignored

**Comment by jvalkeal** [comment] 2016-12-05 08:56
What do you mean by _adding state after s2_? You mean like adding `s3` and then transition between `s2` and `s3`?

**Comment by goldenboyt** [comment] 2016-12-05 09:06
yes, adding for example s3 state after s2 and a transition from s2 to s3

**Comment by jvalkeal** [comment] 2016-12-05 09:08
crap, ok, I'll fix it.

**Comment by jvalkeal** [comment] 2016-12-06 03:15
I couldn't reproduce this, at least by adding that new state as can be shown from above commit. Would you mind showing me a failing test?

**Comment by goldenboyt** [comment] 2016-12-06 11:16
How can i show u a failing test?

**Comment by jvalkeal** [comment] 2016-12-06 11:28
best way is to fork statemachine and put additional test in a different branch(makes it easy for me to pick it up from there). or include zipped attachment to this issue.

**Comment by jvalkeal** [comment] 2016-12-10 15:54
@goldenboyt I'm trying to wrap release next week so if you have issues with this please raise your voice. Otherwise I'm gonna close this ticket.

**Comment by jvalkeal** [comment] 2016-12-14 16:14
Closing, re-open if needed.

**Closed by jvalkeal** 2016-12-14 16:14 UTC
Labels: invalid

**Comment by goldenboyt** [comment] 2016-12-19 06:16
Sorry for my delay (my wedding was last week), I have [forked](https://github.com/goldenboyt/spring-statemachine) state-machine, the bug has gone. Thanks for your support. When can i use binary release?

**Comment by jvalkeal** [comment] 2016-12-19 09:41
oh ok, congrats! 1.2.0.RELEASE is in our repos and central.
