### ISSUE TITLE
Restoring persisted context incorrectly resets state when inside fork

### ISSUE THREAD

**Issue by slithzerikai** [spring-projects/spring-statemachine#242] opened 2016-08-18 10:00 UTC
This occurs when the state is inside a fork, if the context is persisted and then restored, the state of the machine will be reset to the initial state instead of the expected state inside the fork.

This does not occur when persist/restore is bypassed.

I've attached unit test to re-create. Seems to occur on 1.2.0, 1.1.1 and 1.1.0.

[spring-statemachine-bug.zip](https://github.com/spring-projects/spring-statemachine/files/424594/spring-statemachine-bug.zip)

**Comment by jvalkeal** [comment] 2016-08-19 06:56
Thx for pointing this out. I'll try to figure out how to fix this.

**Comment by aldib** [comment] 2016-08-26 12:08
I encountered the same problem and it is preventing us for moving forward. I'll be happy to look into it and try to fix it but I would need to general directions on how states are restored in a FSM with multiple regions. Thanks

**Comment by slithzerikai** [comment] 2016-09-12 12:52
I'm not very familiar with how states are persisted/restored but maybe if you could point me in the general direction of this I could try and have a look at it. I am at a point where I can't go much further without persistence and forks.

**Comment by aldib** [comment] 2016-09-27 09:47
We have reached a dead point in our current project as this bug is preventing us from progressing any further. Fully working persistence is a must have for us as we would be generating in excess of 5 million instances a year.
I fully understand spring-statemachine it's an open project and we are happy to contribute given a little guidance. However, please let us know if the issue is not a priority in the current roadmap as we would need to replace the library with a suitable alternative.

**Comment by jvalkeal** [comment] 2016-09-27 10:15
I'm releasing 1.2.0.M1 prob tomorrow so I think I have more time after that to tackle this issue. Looks like if successfully fixed in master it's a good candidate for backport to 1.1.x.

**Closed** 2016-09-28 08:34 UTC
Labels: bug

**Comment by jvalkeal** [comment] 2016-09-28 08:38
@slithzerikai @aldib  I added one fix which seems to fix issue in attached tests(when run against 1.2.0 snapshots). Lemmy know if it worked for you guys and I backport into 1.1.x, If not please reopen this issue.

**Comment by slithzerikai** [comment] 2016-09-28 11:49
Thanks for this, issue seems to be fixed using the snapshot. Please let me know when you back port it.

**Comment by jvalkeal** [comment] 2016-09-28 17:19
@slithzerikai @aldib 1.1.1.RELEASE is in our repos and on its way to central.
