### ISSUE TITLE
An exception in Action causes infinite transition

### ISSUE THREAD

**Issue by rustock0** [spring-projects/spring-statemachine#344] opened 2017-04-10 16:27 UTC
If any exception occurs inside your `Action`, then Spring State Machine infinitely invokes `Action` that throws the Exception again.

Server Log:
```
2017-04-10 19:11:33.450  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.451  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.453  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.454  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.456  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.457  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.459  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.461  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.462  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.464  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>
2017-04-10 19:11:33.466  WARN 17036 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@60db47a8 caused error <Exception Details>

// infinity
```

In the attached demo, I've prepared simple example to reproduce this issue.
You can invoke deployed REST service using this endpoint http://localhost:8380/doSomething and execute properly configured state machine.
[demo.zip](https://github.com/spring-projects/spring-statemachine/files/910740/demo.zip)

**Comment by jvalkeal** [comment] 2017-04-20 08:53
Good catch, this is indeed caused by loop which is needed to follow anonymous transitions and possible error there ended up with infinite loop. I may need to think about how to properly handle this as it's a bit wrong to just stop execution. I'll handle further tweaks in other tickets and fix this loop issue here.

**Comment by jvalkeal** [comment] 2017-04-20 08:58
Fixed in 1.2.x per https://github.com/spring-projects/spring-statemachine/commit/e25c5c68149662b8ada541ae76ef1028369e28f8

**Comment by rustock0** [comment] 2017-05-11 15:25
Hello,

The fix helped, but now the Action occurred twice. 

Server Log:

```
2017-05-11 18:22:06.061  WARN 20948 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@31441b7e caused error java.lang.NullPointerException: Something was wrong
2017-05-11 18:22:06.062  WARN 20948 --- [nio-8380-exec-1] o.s.s.support.AbstractStateMachine       : Aborting as transition org.springframework.statemachine.transition.DefaultExternalTransition@31441b7e caused error java.lang.NullPointerException: Something was wrong
```

**Comment by jvalkeal** [comment] 2017-05-11 16:00
ok, I'll check it out.

**Comment by rustock0** [comment] 2017-05-22 16:27
Do you have any news about this issue?

**Comment by jvalkeal** [comment] 2017-06-29 12:04
Closing in favour of #384

**Closed by jvalkeal** 2017-06-29 12:04 UTC
Labels: bug
